# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vGReweQbh4xrfn07EvKvK4H63DnCIzPL
"""

#funções de entrada (input) e saída (output)
#print()
#caulculos | expresar numeros | resultado
#palavra = 'Ola Mundo'
#tamanho = len(palavra) # tamanho de atribuição
#print(tamanho)
# a = 5
# d = 'a'
# g = True
# h = 5.3
# b = type(a)
# c = type(d)
# e  = type(g)
# f =  type(h)
# print(b, c)
# str flot int bool
# numero_inteiro = 10.00
# print(type(numero_inteiro))
# real = str(numero_inteiro)
# print(real)
# print(type(real))
# text = ' isso é um texto'
# lista = tuple(text)
# print(lista)
# caractere = lista[8]
# imutavel
# print(caractere)
        # inicio | chegada | a cada quanto
# lista = [1,2,3,4,456,5,6,78,9,10,11,12]
# minimo_da_minha_lista = min(lista)
# maximo_da_minha_lista = max (lista)
# organizar = sorted(lista)
# soma = sum(lista)
# print('minimo-', minimo_da_minha_lista)
# print('Maximo -', maximo_da_minha_lista)
# print('lista organizar', organizar)
# print('Soma da minha lista', soma)
 #Exercicio1:**
#for i in range(2,20):
#   print(i)
#Exercicio2:**
# for i in  range(5,5,50):
#    print(i)
# Exercicio5:**
# for n in  range(-1,11,3):
#    print(n)


# #1 imprima uma mensagem de boas-vindas na tela.
# print('ola, seja ben-vindo(a)!')



# #2 Declare uma variável booleana verdadeira com o valor True e imprima seu tipo.
# booleana = True
# tipo = type(booleana)
# print(tipo)
# # 3 Imprima o resultado da multiplicação de dois números decimais de sua escolha


# print(15.5 * 2.4)


# # 4 Imprima o resultado da divisão de dois números inteiros
# # de sua escolha.
# n1 = 2
# n2= 3
# print(n1/n2)

# # 5 Imprima o resultado da subtração de dois números inteiros de sua escolha

# n3 = 2
# n4 = 3
# print(n3-n4)


# # 6 Imprima o resultado da divisão inteira de dois números inteiros
# # de sua escolha.
# n5 = 2
# n6 = 3
# print(n5*n6)


# # 7 Imprima o resultado da multiplicação de dois números decimais de sua escolha

# n5 = 2
# n6 = 3
# print(n5*n6)


# # 8 Declare uma variável numero e atribua um número inteiro. Em seguida,
# # imprima o dobro desse número

# n= 10
# dobro = n7 ** 2
# print(dobro)


# # 9 Crie uma calculadora de soma com as ferramentas que vc já
# # conhece(Use apenas input, print e variavel)

# numero1 = float('input('>>')')
# numero2 = float('input('>>')')
# soma = numero1 + numero2
# print (f'soma {soma}')


# # 10 Crie um sistema de cadastro com as estruturas que vc já
# # conhece(Use apenas input, print e variavel)

# print('Formulário de cadastro:')

# nome = input('>>')
# cpf =   input('>>')
# email = input('>>')
# endereco = input('>>')

# print(f'''
# Dados do fiormulário, deseja eviar?
# {nome}
# {cpf}
# {email}
# {endereco}55
# ''')